### ISSUE TITLE
Getting this issue after running the SDK

### ISSUE THREAD

**Issue by pushpal007** [Estimote/Android-Indoor-SDK#10]
W/System.err: io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
W/System.err:     at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
W/System.err:     at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
W/System.err:     at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
W/System.err:     at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
W/System.err:     at io.reactivex.internal.subscribers.BasicFuseableSubscriber.fail(BasicFuseableSubscriber.java:111)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:66)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RepeatSubscriber.onNext(FlowableRetryPredicate.java:71)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err:   ComposedException 1 :
W/System.err: 	kotlin.KotlinNullPointerException
W/System.err:     at com.estimote.indoorsdk_module.algorithm.e.c.a(Unknown Source)
W/System.err:     at com.estimote.indoorsdk_module.algorithm.e.c.a(Unknown Source)
W/System.err:     at com.estimote.indoorsdk_module.algorithm.a$h.a(Unknown Source)
W/System.err:     at com.estimote.indoorsdk_module.algorithm.a$h.apply(Unknown Source)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RepeatSubscriber.onNext(FlowableRetryPredicate.java:71)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err:   ComposedException 2 :
W/System.err: 	java.lang.NullPointerException: println needs a message
W/System.err:     at android.util.Log.println_native_inner(Native Method)
W/System.err:     at android.util.Log.println_native(Log.java:290)
W/System.err:     at android.util.Log.d(Log.java:323)
W/System.err:     at com.estimote.indoorsdk_module.algorithm.a$3.a(Unknown Source)
W/System.err:     at com.estimote.indoorsdk_module.algorithm.a$3.accept(Unknown Source)
W/System.err:     at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:76)
W/System.err:     at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
W/System.err:     at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
W/System.err:     at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
W/System.err:     at io.reactivex.internal.subscribers.BasicFuseableSubscriber.fail(BasicFuseableSubscriber.java:111)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:66)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RepeatSubscriber.onNext(FlowableRetryPredicate.java:71)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-1
                  Process: com.estimote.indoorapp, PID: 3333
                  io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
                      at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
                      at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
                      at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
                      at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
                      at io.reactivex.internal.subscribers.BasicFuseableSubscriber.fail(BasicFuseableSubscriber.java:111)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:66)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                      at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RepeatSubscriber.onNext(FlowableRetryPredicate.java:71)
                      at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
                      at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
                      at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                      at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
                    ComposedException 1 :
                  	kotlin.KotlinNullPointerException
                      at com.estimote.indoorsdk_module.algorithm.e.c.a(Unknown Source)
                      at com.estimote.indoorsdk_module.algorithm.e.c.a(Unknown Source)
                      at com.estimote.indoorsdk_module.algorithm.a$h.a(Unknown Source)
                      at com.estimote.indoorsdk_module.algorithm.a$h.apply(Unknown Source)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                      at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RepeatSubscriber.onNext(FlowableRetryPredicate.java:71)
                      at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
                      at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
                  		at io.reactivex.internal.sch

**Comment by pushpal007** [comment]
This is the ANdroid Runtime error that is occuring:

E/AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-1
                                                                        Process: com.estimote.indoorapp, PID: 19625
                                                                        io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
                                                                            at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
                                                                            at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
                                                                            at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
                                                                            at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
                                                                            at io.reactivex.internal.subscribers.BasicFuseableSubscriber.fail(BasicFuseableSubscriber.java:111)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:66)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RepeatSubscriber.onNext(FlowableRetryPredicate.java:71)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
                                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                          ComposedException 1 :
                                                                        	kotlin.KotlinNullPointerException
                                                                            at com.estimote.indoorsdk_module.algorithm.e.c.a(Unknown Source)
                                                                            at com.estimote.indoorsdk_module.algorithm.e.c.a(Unknown Source)
                                                                            at com.estimote.indoorsdk_module.algorithm.a$h.a(Unknown Source)
                                                                            at com.estimote.indoorsdk_module.algorithm.a$h.apply(Unknown Source)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RepeatSubscriber.onNext(FlowableRetryPredicate.java:71)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
                                                                        		at io.reactivex.internal.sc

Let me know any possible solution. 

Development environment: Android Studio : 2.2.3, JRE: 1.8.0_76

**Comment by pawelDylag** [comment]
Hello @pushpal007 

Thanks for reporting this issue. Could you verify that this is still happening in version `2.0.1`? 

Regards, 
Paweł

**Comment by pushpal007** [comment]
Hi,

Thanks for your response.

Yes, this is happening in the latest android SDK released.

compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
compile 'io.reactivex.rxjava2:rxjava:2.1.0'

Thanks

**Comment by pawelDylag** [comment]
@pushpal007  
I don't think this is a problem with AS. I think it may be some problem with your `Location` setup.
Can you check, that your `Location` object is not empty - does it contain beacon data? You may paste here your location object, it may be easier for me to check it. 

Regards, 
Paweł

**Comment by pushpal007** [comment]
Here is the Location Object details:

 Location(name=Pushpal.Mukherjee's location, identifier=pushpal-mukherjee-s-location, public=false, owner=pushpal.mukherjee@capgemini.com, orientation=112.213623799198, walls=[LocationWall(x1=-0.504106579161061, y1=-0.670328319181244, x2=-0.475846124725085, y2=3.9532198402839, orientation=90.3502039010698), LocationWall(x1=-0.475846124725085, y1=3.9532198402839, x2=2.49284921634527, y2=4.0736151557831, orientation=177.677644694414), LocationWall(x1=2.49284921634527, y1=4.0736151557831, x2=3.5967211371517, y2=0.541412792444948, orientation=252.645108171261), LocationWall(x1=3.5967211371517, y1=0.541412792444948, x2=-0.504106579161061, y2=-0.670328319181244, orientation=343.538277141258)], beacons=[LocationBeacon(beacon=LocationBeaconData(mac=de543f36335970d1ded1ec475b650c3c, color=Sweet Beetroot), position=LocationPosition(x=0.159811485686227, y=3.97899890811083, orientation=177.677644694414)), LocationBeacon(beacon=LocationBeaconData(mac=ac66e4cc101f43bd971a98f06c91da3c, color=Sweet Beetroot), position=LocationPosition(x=0.305365835610109, y=-0.431139776877033, orientation=343.538277141258)), LocationBeacon(beacon=LocationBeaconData(mac=41ece2d381491b3cc314e3dfe994dc02, color=Candy Floss), position=LocationPosition(x=3.05151437529792, y=2.28598168348168, orientation=252.645108171261)), LocationBeacon(beacon=LocationBeaconData(mac=2f4f5aec3cac8fca73218f499cba1511, color=Lemon Tart), position=LocationPosition(x=-0.478387461165266, y=3.53744480569621, orientation=90.3502039010698))], linearObjects=[])

Thanks

**Comment by pawelDylag** [comment]
Thanks @pushpal007 

Your location seems fine. I will need info about your phone then: 

1. Android phone model
2. Android OS version

If there is a possibility - could you verify if this error occurs on any different Android phone? 

Regards, 
Paweł

**Comment by pushpal007** [comment]
Hi Pawel,

I have tested this on Moto G (3rd generation) and the OS version is 6.0.1.

I will test it on other device and let you know the update.

Thanks

**Comment by pushpal007** [comment]
Hi,

I have tested the app in Moto Z Play and the OS version is 7.1.1, but the app keeps stopping with the same exceptions.

Thanks

**Comment by pushpal007** [comment]
Hi Pawel, 

Is there any update on the issue. Looking forward to hear from your side.

Thanks

**Comment by pawelDylag** [comment]
Hey @pushpal007 - we will investigate this deeper in the next week. As far as I know, Moto phones had some BLE scanning problems due to the custom ROM. Can you verify it on any other phone? Also, are you building a native Android app, or using something like Cordova/Xamarin, or React Native?

**Comment by pushpal007** [comment]
Hi Pawel,

We are developing a native android app using location beacons. 

Thanks

**Comment by pushpal007** [comment]
Hi,

Have tested on HTC Desire 526 plus with OS version 4.4.2 and the issue occurred.

Thanks

**Comment by pushpal007** [comment]
Hey Pawel,
Have you guys checked the issue and is there any update at your end. Looking forward to hear from your side.
Thanks

**Comment by pawelDylag** [comment]
Hey @pushpal007 !

Sorry for the delay.  There is a new version available (`2.1.0`) with this problem fixed. Please verify it and tell me if everything is ok now :)

Also we added flag for enabling debug logs:
``` Kotlin
// since version 2.1.0 there is a third boolean parameter for enabling debug logging
indoorLocationManager = IndoorLocationManager.create(applicationContext, mLocation, true)
```
You can enable it and send us scanning logs when having any problems :)
Regards, 
Paweł

**Comment by pushpal007** [comment]
Hi Pawel,

Thanks for your response. We will test the new version at our end and let you know update on the same.

Thanks

**Comment by pushpal007** [comment]
Hi Pawel,

Still the issue remains. Here is the error log.

01-31 17:30:47.197 26426-26590/com.estimote.indoorapp E/AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-1
                                                                        Process: com.estimote.indoorapp, PID: 26426
                                                                        io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
                                                                            at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:82)
                                                                            at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
                                                                            at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
                                                                            at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
                                                                            at io.reactivex.internal.subscribers.BasicFuseableSubscriber.fail(BasicFuseableSubscriber.java:111)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:66)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RepeatSubscriber.onNext(FlowableRetryPredicate.java:71)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
                                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                            at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                          ComposedException 1 :
                                                                        	kotlin.KotlinNullPointerException
                                                                            at com.estimote.indoorsdk_module.algorithm.e.c.a(Unknown Source)
                                                                            at com.estimote.indoorsdk_module.algorithm.e.c.a(Unknown Source)
                                                                            at com.estimote.indoorsdk_module.algorithm.a$h.a(Unknown Source)
                                                                            at com.estimote.indoorsdk_module.algorithm.a$h.apply(Unknown Source)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
                                                                            at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                                                                            at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RepeatSubscriber.onNext(FlowableRetryPredicate.java:71)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)
                                                                            at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
                                                                        		at io.reactivex.internal.sc

Thanks

**Comment by pushpal007** [comment]
Hi Pawel,

Is there any update on the same. Do I have to upgrade to AS 3 in order to run the SDK?

Thanks

**Comment by pushpal007** [comment]
Hi Pawel,

We are looking forward to hear from your side regarding the issue. Is there any update.

Thanks
