### ISSUE TITLE
scanningIndoorLocationManager Not initialized 

### ISSUE THREAD

**Issue by elangosaravanan21** [Estimote/Android-Indoor-SDK#8]
![estimote](https://user-images.githubusercontent.com/26079468/31493275-1cf36dfa-af6c-11e7-809e-69426ff3d667.png)
When im running the app **Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter location
                                                                                               at com.estimote.indoorsdk.algorithm.IndoorLocationManagerBuilder.<init>(Unknown Source)
                                                                                               at com.saravanastores.seehash.saravanastores.MainActivity.onCreate(MainActivity.java:32)**

please help me to solve the error, im using java code only not kotlin

**Comment by pawelDylag** [comment]
Hey! Checkout the version `2.0.0` we released today. Tell me if your problem still exists.
Remember that all parameters passed to the Kotlin code must not be null. Double-check that your Context/Location/Credentials objects are not null - otherwise Kotlin will throw this error `IllegalArgumentException: Parameter specified as non-null is null`

**Comment by pawelDylag** [comment]
Hey @elangosaravanan21 

Could you make sure, that when using below fragment in your code, the parameter `location` is not null? Could you log it somewhere before creating our `ScanningIndoorLocationManager?

```
ScanningIndoorLocationManager indoorLocationManager = 
    new IndoorLocationManagerBuilder(this, location, cloudCredentials)
    .withDefaultScanner()
    .build();
```

**Comment by elangosaravanan21** [comment]
package com.saravanastores.seehash.saravanastores;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;

import com.estimote.indoorsdk.IndoorLocationManagerBuilder;
import com.estimote.indoorsdk_module.algorithm.OnPositionUpdateListener;
import com.estimote.indoorsdk_module.algorithm.ScanningIndoorLocationManager;
import com.estimote.indoorsdk_module.cloud.CloudCallback;
import com.estimote.indoorsdk_module.cloud.EstimoteCloudException;
import com.estimote.indoorsdk_module.cloud.IndoorCloudManager;
import com.estimote.indoorsdk_module.cloud.IndoorCloudManagerFactory;
import com.estimote.indoorsdk_module.cloud.Location;
import com.estimote.indoorsdk_module.cloud.LocationPosition;
import com.estimote.indoorsdk_module.view.IndoorLocationView;
import com.estimote.internal_plugins_api.cloud.CloudCredentials;
import com.estimote.cloud_plugin.common.EstimoteCloudCredentials;


public class MainActivity extends AppCompatActivity {


    IndoorLocationView indoorLocationView;
    Location loc;
    ScanningIndoorLocationManager indoorLocationManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        indoorLocationView = (IndoorLocationView) findViewById(R.id.indoor_view);
        //indoorLocationView.setLocation(location);

        final CloudCredentials cloudCredentials = new EstimoteCloudCredentials("ankit-seehash-com-s-your-o-fsn", "6528a1f6c8115368959817db16b32729");
        IndoorCloudManager cloudManager = new IndoorCloudManagerFactory().create(this, cloudCredentials);
        cloudManager.getLocation("ankit-s-location-m8f", new CloudCallback<Location>() {
            @Override
            public void success(Location location) {
                // do something with your Location object here.
                // You will need it to initialise IndoorLocationManager!
                indoorLocationView = (IndoorLocationView) findViewById(R.id.indoor_view);
                indoorLocationView.setLocation(location);
                loc = location;

                Log.d("locationlocation", "" + location);
                indoorLocationManager =
                        new IndoorLocationManagerBuilder(getApplicationContext(), location, cloudCredentials)
                                .withDefaultScanner()
                                .build();

                indoorLocationManager.setOnPositionUpdateListener(new OnPositionUpdateListener() {
                    @Override
                    public void onPositionUpdate(LocationPosition locationPosition) {
                        indoorLocationView.updatePosition(locationPosition);
                    }

                    @Override
                    public void onPositionOutsideLocation() {


                        indoorLocationView.hidePosition();
                    }
                });
            }

            @Override
            public void failure(EstimoteCloudException e) {
                // oops!
            }
        });


    }

    @Override
    protected void onStart() {
        super.onStart();

    }

    @Override
    protected void onStop() {
        super.onStop();

    }
}



**# This is my full code i cant view my current position in map.but it shows my map.**

**Comment by elangosaravanan21** [comment]
PositionOutside location called every time.even its inside location.

**Comment by pawelDylag** [comment]
Hey @elangosaravanan21  you are missing `indoorLocartionManager.startPositioning()` inside your `onStart()` method. Also make sure, that your beacons have EstimoteLocation packet advertising enabled.

**Comment by elangosaravanan21** [comment]
Thank you for replying me.I found that error.but if I put start positioning in an Onstart method null object reference come.
