### ISSUE TITLE
Issue with 4.4.2

### ISSUE THREAD

**Issue by ankushpatel18** [Estimote/Android-Indoor-SDK#9]
Unable to run application in Android OS version 4.4.2, application crashes again and again.

Here is log details

2-22 13:52:38.186 6290-6290/com.estimote.indoorapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.estimote.indoorapp, PID: 6290
                                                                      java.lang.NoSuchMethodError: android.bluetooth.BluetoothAdapter.getBluetoothLeScanner
                                                                          at com.estimote.scanning_sdk.dagger.BluetoothModule.providesBluetoothLeScanner(BluetoothModule.kt:28)
                                                                          at com.estimote.scanning_sdk.dagger.BluetoothModule_ProvidesBluetoothLeScannerFactory.get(BluetoothModule_ProvidesBluetoothLeScannerFactory.java:31)
                                                                          at com.estimote.scanning_sdk.dagger.BluetoothModule_ProvidesBluetoothLeScannerFactory.get(BluetoothModule_ProvidesBluetoothLeScannerFactory.java:10)
                                                                          at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                          at com.estimote.scanning_sdk.dagger.ScannerModule_ProvideScannerFactoryFactory.get(ScannerModule_ProvideScannerFactoryFactory.java:30)
                                                                          at com.estimote.scanning_sdk.dagger.ScannerModule_ProvideScannerFactoryFactory.get(ScannerModule_ProvideScannerFactoryFactory.java:10)

**Comment by pawelDylag** [comment]
Hey @ankushpatel18 

We have been a little busy, sorry for the delay ^^
After update to `2.0.0` our SDK works only with Android 5.0+ devices. The BLE scanning stack on KitKat devices is not reliable. Anyway, we updated our SDK not to crash on KitKat - it will simply not scan.

Regards, 
Paweł
